### ISSUE TITLE
USB C port

### ISSUE THREAD

**Issue by tommyw1979** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#2]
this does not seem to be recognsed when I plug anythhing into it?

**Comment by 5T33Z0** [comment]
The [Additional Files Sections](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/tree/main/Additional%20Files) contains a Files called USB_ports.ziü containing all the Info and files abour which ports are mapped. And due to the 15 Port Limit USB C is not mapped. So if you want to use USB C you need to map it yourself using Hackintool.
