### ISSUE TITLE
Get stuck after installing eGPU (PCI Configuration Begin)

### ISSUE THREAD

**Issue by trimal2** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#3]
Installed Big Sur 11.5 with your guide. Only difference in build is my CPU is i5 and I had used only internal GPU. Added framebuffer and everything went smoothly, thank you very much.
After buying and  installing a eGPU (RX 580) and changing iGPU to headless mode in config. System get stuck at "PCI configuration begin" message.
Maybe you can point me in a right way how it could be fixed.
Thank you in advance.

**Comment by 5T33Z0** [comment]
The Card should work oob. Check the following:

- Does Windows boot with the card? If not it may not be seated correctly in the socket
- Disable iGPU in BIOS
- Disable corresponding Frambuffer-Patch in config
- Change SMBIOS to iMac20,1 (because you use an i5). **NOTE**: Changing SMBIOS may require re-mapping the USB ports!
- Disable CPUFriend and the DataProvider kexts or create your own for your CPU
- Disable AGPM Injector kext or create own for your GPU
- Try boot-arg shikigva=80

Since I don't use an AMD Card I can't help you any further. If the problem persits please look for help in the usual hackintosh forums.

**Comment by trimal2** [comment]
Thank you very much for you response.
The machine was in working condition with correct  iMac20,1 smbios, cpu friend and data provider. 
Will try and will post a solution here once found.
