### ISSUE TITLE
USB Mapping

### ISSUE THREAD

**Issue by kuczynsky** [5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore#30]
Hi,

Thank you for the great work - so far it works fine on my Z490 Vision G with i7-10700K & R9 380 GPU.
One question though: is there a reason why the rear USB-C port is not mapped?

**Comment by 5T33Z0** [comment]
Check the [Additional Files Section](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/tree/main/Additional_Files) for a List of mapped USB Ports and a zip with a USB Ports kext.

**Comment by mroncetwice** [comment]
I see this issue is closed, but hoping to get some help. This EFI is great, but I am not able to connect to USB-C devices nor am I seeing USB-C in System Report. 

Everything else, besides ethernet, seems to work great. Im using a Z490 Vision G, i9-10850k, and Sapphire RX580.

**Comment by kuczynsky** [comment]
Hi,

Due to the port limit, USB-C is not mapped there. I have tried to map it by sacrificing some other USB ports, but I have encountered the wakelocks and decided not to proceed - not a big deal for me as I do not have any devices that would connect to that port.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 5T33Z0** [comment]
USB-C is not mapped since I don't use it. It has ports HS06 and SS06. 

You can check the list of mapped ports here: https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/Additional_Files/USB_Ports_List.pdf

You could – for example – disable the 2 USB 2.0-only ports `HS 11` and `SS 13` following my ACPI Port Mapping [guide](https://github.com/5T33Z0/OC-Little-Translated/tree/main/03_USB_Fixes/ACPI_Mapping_USB_Ports#mapping-the-ports-finally) and then re-enable HS06 and SS06 by deleting the  If (_OSI ("Darwin")) section from methods `_UPC` and `_PLD`. The port type is `0x09` (USB C with a switch).
